[2025-04-20T23:36:30.440+0800] {processor.py:186} INFO - Started process (PID=177947) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:36:30.443+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:36:30.447+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:36:30.445+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:36:30.539+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:36:30.507+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:36:30.547+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:36:30.636+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.224 seconds
[2025-04-20T23:37:36.792+0800] {processor.py:186} INFO - Started process (PID=178421) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:37:36.795+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:37:36.802+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:37:36.799+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:37:36.861+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:37:36.837+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:37:36.878+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:37:36.987+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.216 seconds
[2025-04-20T23:38:48.254+0800] {processor.py:186} INFO - Started process (PID=178907) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:38:48.259+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:38:48.267+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:38:48.263+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:38:48.329+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:38:48.309+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:38:48.334+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:38:48.407+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.186 seconds
[2025-04-20T23:39:57.526+0800] {processor.py:186} INFO - Started process (PID=179452) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:39:57.528+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:39:57.533+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:39:57.531+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:39:57.582+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:39:57.563+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:39:57.586+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:39:57.671+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.171 seconds
[2025-04-20T23:41:01.803+0800] {processor.py:186} INFO - Started process (PID=180004) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:41:01.805+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:41:01.809+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:41:01.808+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:41:01.857+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:41:01.843+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:41:01.861+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:41:01.921+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.137 seconds
[2025-04-20T23:42:10.339+0800] {processor.py:186} INFO - Started process (PID=180551) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:42:10.341+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:42:10.346+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:42:10.344+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:42:10.383+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:42:10.371+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:42:10.388+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:42:10.474+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.155 seconds
[2025-04-20T23:43:21.514+0800] {processor.py:186} INFO - Started process (PID=181033) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:43:21.517+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:43:21.521+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:43:21.519+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:43:21.562+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:43:21.548+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:43:21.568+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:43:21.637+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.144 seconds
[2025-04-20T23:44:24.554+0800] {processor.py:186} INFO - Started process (PID=181734) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:44:24.557+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:44:24.561+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:44:24.559+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:44:24.617+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:44:24.596+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:44:24.622+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:44:24.695+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.162 seconds
[2025-04-20T23:45:21.646+0800] {processor.py:186} INFO - Started process (PID=182424) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:45:21.649+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:45:21.653+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:45:21.651+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:45:21.698+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:45:21.681+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:45:21.703+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:45:21.763+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.135 seconds
[2025-04-20T23:46:20.215+0800] {processor.py:186} INFO - Started process (PID=183113) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:46:20.224+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:46:20.229+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:46:20.227+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:46:20.274+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:46:20.255+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:46:20.278+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:46:20.343+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.188 seconds
[2025-04-20T23:47:29.107+0800] {processor.py:186} INFO - Started process (PID=183807) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:47:29.110+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:47:29.115+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:47:29.114+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:47:29.164+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:47:29.147+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:47:29.174+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:47:29.253+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.169 seconds
[2025-04-20T23:48:43.484+0800] {processor.py:186} INFO - Started process (PID=184289) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:48:43.488+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:48:43.498+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:48:43.496+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:48:43.553+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:48:43.534+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:48:43.559+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:48:43.637+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.186 seconds
[2025-04-20T23:49:59.066+0800] {processor.py:186} INFO - Started process (PID=184916) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:49:59.068+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:49:59.072+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:49:59.071+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:49:59.119+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:49:59.101+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:49:59.123+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:49:59.187+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.144 seconds
[2025-04-20T23:51:10.092+0800] {processor.py:186} INFO - Started process (PID=185391) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:51:10.096+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:51:10.103+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:51:10.099+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:51:10.158+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:51:10.140+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:51:10.161+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:51:10.238+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.175 seconds
[2025-04-20T23:52:31.364+0800] {processor.py:186} INFO - Started process (PID=185873) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:52:31.368+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:52:31.379+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:52:31.371+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:52:31.436+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:52:31.419+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:52:31.443+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:52:31.575+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.247 seconds
[2025-04-20T23:53:42.763+0800] {processor.py:186} INFO - Started process (PID=186355) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:53:42.766+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:53:42.771+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:53:42.769+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:53:42.835+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:53:42.809+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:53:42.841+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:53:42.924+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.187 seconds
[2025-04-20T23:54:51.590+0800] {processor.py:186} INFO - Started process (PID=186832) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:54:51.593+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:54:51.598+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:54:51.596+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:54:51.652+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:54:51.636+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:54:51.658+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:54:51.753+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.192 seconds
[2025-04-20T23:56:02.535+0800] {processor.py:186} INFO - Started process (PID=187353) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:56:02.537+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:56:02.543+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:56:02.540+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:56:02.623+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:56:02.586+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:56:02.627+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:56:02.778+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.266 seconds
[2025-04-20T23:57:15.207+0800] {processor.py:186} INFO - Started process (PID=187835) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:57:15.211+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py for tasks to queue
[2025-04-20T23:57:15.217+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:57:15.216+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:57:15.278+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:57:15.257+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon'
[2025-04-20T23:57:15.286+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py
[2025-04-20T23:57:15.370+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dag_with_minio_s3.py took 0.188 seconds
