[2025-04-20T23:46:30.530+0800] {processor.py:186} INFO - Started process (PID=183264) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:46:30.532+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:46:30.536+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:46:30.535+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:46:30.603+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:46:30.586+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:46:30.607+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:46:30.693+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.183 seconds
[2025-04-20T23:47:27.506+0800] {processor.py:186} INFO - Started process (PID=183806) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:47:27.509+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:47:27.518+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:47:27.516+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:47:27.556+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:47:27.542+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:47:27.559+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:47:27.633+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.146 seconds
[2025-04-20T23:48:41.976+0800] {processor.py:186} INFO - Started process (PID=184288) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:48:41.979+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:48:41.986+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:48:41.984+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:48:42.049+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:48:42.029+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:48:42.063+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:48:42.152+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.206 seconds
[2025-04-20T23:49:57.679+0800] {processor.py:186} INFO - Started process (PID=184915) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:49:57.683+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:49:57.687+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:49:57.685+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:49:57.729+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:49:57.714+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:49:57.733+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:49:57.817+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.157 seconds
[2025-04-20T23:51:08.581+0800] {processor.py:186} INFO - Started process (PID=185360) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:51:08.587+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:51:08.593+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:51:08.591+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:51:08.655+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:51:08.633+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:51:08.660+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:51:08.770+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.211 seconds
[2025-04-20T23:52:29.282+0800] {processor.py:186} INFO - Started process (PID=185872) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:52:29.286+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:52:29.295+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:52:29.294+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:52:29.364+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:52:29.341+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:52:29.372+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:52:29.563+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.352 seconds
[2025-04-20T23:53:41.239+0800] {processor.py:186} INFO - Started process (PID=186353) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:53:41.244+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:53:41.254+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:53:41.251+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:53:41.304+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:53:41.284+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:53:41.308+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:53:41.403+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.188 seconds
[2025-04-20T23:54:51.175+0800] {processor.py:186} INFO - Started process (PID=186831) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:54:51.179+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:54:51.183+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:54:51.182+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:54:51.231+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:54:51.213+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:54:51.236+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:54:51.319+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.173 seconds
[2025-04-20T23:56:01.505+0800] {processor.py:186} INFO - Started process (PID=187313) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:56:01.507+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:56:01.512+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:56:01.510+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:56:01.573+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:56:01.547+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:56:01.578+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:56:01.668+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.185 seconds
[2025-04-20T23:57:13.747+0800] {processor.py:186} INFO - Started process (PID=187795) to work on /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:57:13.750+0800] {processor.py:914} INFO - Processing file /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py for tasks to queue
[2025-04-20T23:57:13.755+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:57:13.753+0800] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:57:13.813+0800] {logging_mixin.py:190} INFO - [2025-04-20T23:57:13.792+0800] {dagbag.py:387} ERROR - Failed to import: /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
Traceback (most recent call last):
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py", line 8, in <module>
    from airflow.providers.postgres.hooks.postgres import PostgresHook
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2025-04-20T23:57:13.820+0800] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py
[2025-04-20T23:57:13.896+0800] {processor.py:208} INFO - Processing /mnt/c/Users/wu_li/OneDrive/Desktop/Airflow_pract/dags/dags_with_postgres_hook.py took 0.172 seconds
